### ISSUE TITLE
Support for Nested Preemption in nxtOSEK

### ISSUE THREAD

**Issue by khchenTW** [ev3osek/ev3osek#8]
This issue might be similar as Ecrobot_wait bug #6. In the past, I used nxtOSEK but found that there is a fatal bug in the kernel. That is the nested preemption is not feasible. The attached references are the latest results (2014) in nxtOSEK. They couldn't fully solve the bug. Is this issue is still there in ev3osek?

http://www4.ncsu.edu/~sgupta20/pts.html
[http://www4.ncsu.edu/~sgupta20/final.pdf](url)

**Comment by fgr** [comment]
Thank you for pointing out the bug in the nxtOSEK kernel. It is very likely that ev3osek suffers the same bug since ev3osek is a port of nxtOSEK (to the Mindstroms EV3).

I will read the documents you referred to in order to understand more about the problem so we might be able to fix it. However, ev3osek is a research project and at the moment we are lacking developers who can work on it. And since the nxtOSEK team could not fix the bug, I'm not hopeful that we can do so.

**Comment by khchenTW** [comment]
Thanks for your reply. In fact our group is seeking a portation of nxtOSEK and just notice that here is the solution :+1: 

Then, we are going to solve that problem based on your EV3OSEK version. Hopefully we can come out some sketches after putting some efforts.

**Comment by fgr** [comment]
It's great that you decided to use ev3osek as a starting point. We are always happy to help, so please don't hesitate to get in touch with us...

**Comment by fgr** [comment]
Issues closed by PR #10.
